### ISSUE TITLE
Optimize front-end for website

### ISSUE THREAD

**Issue by sbshah97** [piyushnbansal/RajHousing#3]
* Front end can further be improved for higher rank on PageSpeed Insights. To see the full report for each of the pages click on the following links:
[Home Page](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Frajhousing.in%2F&tab=mobile)
[Projects Page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frajhousing.in%2Fprojects.html&tab=mobile)
[About Us](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frajhousing.in%2Fabout.html)

![raj-housing-1](https://user-images.githubusercontent.com/16410361/30314569-bc6c673a-97be-11e7-9bf2-b40cffc5a40d.png)
Home Page Report - Desktop

![raj-housing-2](https://user-images.githubusercontent.com/16410361/30314568-bc667262-97be-11e7-97ca-a95b7e823d3a.png)
Home Page Report - Mobile

One additional suggestion is to use minimized CSS files rather than calling the entire file and render the JavaScript at the end of the HTML rather than at the beginning. Helps in Page Optimisation!

**Comment by sbshah97** [comment]
@isunitha98selvan try to solve this as well if possible!

**Comment by sbshah97** [comment]
@isunitha98selvan I think this is also covered in #9

**Comment by sunitharavi9** [comment]
Yeah. Browser caching can't be enabled for gh pages. Everything else is covered.

**Comment by sbshah97** [comment]
Cool
