### ISSUE TITLE
SEO For website

### ISSUE THREAD

**Issue by sbshah97** [piyushnbansal/RajHousing#5]
Add the following:
- [x] Meta tags in head of each file
- [ ] Alternative text for all the images! (If possible code it with the JSON itself if it's dynamic rendering)
- [ ] JSON-LD data if possible as well as rich cards
- [x] `robots.txt` file 
- [x] `sitemap.xml` file
- [ ] Create a Analytics+Webmaster account and request indexing for the root page

Ping me if you need any help over here

**Comment by sbshah97** [comment]
All of this done @isunitha98selvan ?

**Comment by sunitharavi9** [comment]
Yeah. Everything is done.
